import type { ConnType } from '../types'

const COMMON_SQL_FUNCTIONS = [
  'COALESCE', 'NULLIF', 'CAST', 'CONVERT', 'ABS', 'CEIL', 'CEILING', 'FLOOR', 'ROUND',
  'TRUNC', 'LENGTH', 'LOWER', 'UPPER', 'TRIM', 'LTRIM', 'RTRIM', 'SUBSTRING', 'REPLACE',
  'CONCAT', 'COUNT', 'SUM', 'AVG', 'MIN', 'MAX', 'ROW_NUMBER', 'RANK', 'DENSE_RANK',
  'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP',
]

const DIALECT_SQL_FUNCTIONS: Partial<Record<ConnType, string[]>> = {
  mysql: ['ADDDATE', 'SUBDATE', 'DATE_ADD', 'DATE_SUB', 'DATEDIFF', 'TIMEDIFF', 'TIMESTAMPDIFF', 'TIMESTAMPADD', 'DATE_FORMAT', 'STR_TO_DATE', 'DAY', 'MONTH', 'YEAR', 'NOW', 'CURDATE', 'CURTIME', 'IF', 'IFNULL', 'GROUP_CONCAT', 'FIND_IN_SET', 'JSON_EXTRACT', 'JSON_OBJECT', 'JSON_ARRAY', 'JSON_UNQUOTE'],
  mariadb: ['ADDDATE', 'SUBDATE', 'DATE_ADD', 'DATE_SUB', 'DATEDIFF', 'TIMEDIFF', 'TIMESTAMPDIFF', 'TIMESTAMPADD', 'DATE_FORMAT', 'STR_TO_DATE', 'DAY', 'MONTH', 'YEAR', 'NOW', 'CURDATE', 'CURTIME', 'IF', 'IFNULL', 'GROUP_CONCAT', 'FIND_IN_SET', 'JSON_EXTRACT', 'JSON_OBJECT', 'JSON_ARRAY', 'JSON_UNQUOTE'],
  tidb: ['ADDDATE', 'SUBDATE', 'DATE_ADD', 'DATE_SUB', 'DATEDIFF', 'TIMEDIFF', 'TIMESTAMPDIFF', 'TIMESTAMPADD', 'DATE_FORMAT', 'STR_TO_DATE', 'DAY', 'MONTH', 'YEAR', 'NOW', 'CURDATE', 'CURTIME', 'IF', 'IFNULL', 'GROUP_CONCAT', 'FIND_IN_SET', 'JSON_EXTRACT', 'JSON_OBJECT', 'JSON_ARRAY'],
  oceanBase: ['ADDDATE', 'SUBDATE', 'DATE_ADD', 'DATE_SUB', 'DATEDIFF', 'TIMEDIFF', 'TIMESTAMPDIFF', 'TIMESTAMPADD', 'DATE_FORMAT', 'STR_TO_DATE', 'DAY', 'MONTH', 'YEAR', 'NOW', 'CURDATE', 'CURTIME', 'IF', 'IFNULL', 'GROUP_CONCAT', 'FIND_IN_SET'],
  postgres: ['AGE', 'DATE_TRUNC', 'DATE_PART', 'EXTRACT', 'TO_CHAR', 'TO_DATE', 'TO_TIMESTAMP', 'NOW', 'STRING_AGG', 'ARRAY_AGG', 'JSON_BUILD_OBJECT', 'JSONB_BUILD_OBJECT', 'REGEXP_REPLACE', 'GENERATE_SERIES'],
  kingBase: ['AGE', 'DATE_TRUNC', 'DATE_PART', 'EXTRACT', 'TO_CHAR', 'TO_DATE', 'TO_TIMESTAMP', 'NOW', 'STRING_AGG', 'ARRAY_AGG', 'REGEXP_REPLACE'],
  openGauss: ['AGE', 'DATE_TRUNC', 'DATE_PART', 'EXTRACT', 'TO_CHAR', 'TO_DATE', 'TO_TIMESTAMP', 'NOW', 'STRING_AGG', 'ARRAY_AGG', 'REGEXP_REPLACE'],
  sqlServer: ['DATEADD', 'DATEDIFF', 'DATEDIFF_BIG', 'DATEPART', 'DATENAME', 'GETDATE', 'SYSDATETIME', 'ISNULL', 'IIF', 'STRING_AGG', 'STRING_SPLIT', 'PATINDEX', 'CHARINDEX', 'NEWID'],
  oracle: ['ADD_MONTHS', 'MONTHS_BETWEEN', 'LAST_DAY', 'NEXT_DAY', 'TRUNC', 'TO_CHAR', 'TO_DATE', 'TO_TIMESTAMP', 'SYSDATE', 'SYSTIMESTAMP', 'NVL', 'NVL2', 'DECODE', 'LISTAGG', 'REGEXP_REPLACE'],
  sqlite: ['DATE', 'TIME', 'DATETIME', 'JULIANDAY', 'UNIXEPOCH', 'STRFTIME', 'IFNULL', 'IIF', 'PRINTF', 'GLOB', 'TOTAL', 'RANDOM', 'JSON_EXTRACT', 'JSON_OBJECT', 'JSON_ARRAY'],
  duckdb: ['DATE_TRUNC', 'DATE_PART', 'DATE_DIFF', 'DATE_ADD', 'STRFTIME', 'STRPTIME', 'STRING_AGG', 'LIST', 'LIST_AGGREGATE', 'REGEXP_REPLACE', 'JSON_EXTRACT'],
  clickHouse: ['ADD_DAYS', 'SUB_DAYS', 'ADD_MONTHS', 'SUB_MONTHS', 'ADD_YEARS', 'SUB_YEARS', 'TO_DATE', 'TO_DATETIME', 'NOW', 'TODAY', 'DATE_DIFF', 'FORMAT_DATETIME', 'GROUP_ARRAY', 'ARRAY_JOIN', 'IFNULL'],
}

export function sqlFunctionsForDialect(connType: ConnType): string[] {
  return Array.from(new Set([...(DIALECT_SQL_FUNCTIONS[connType] ?? []), ...COMMON_SQL_FUNCTIONS]))
}
